### ISSUE TITLE
Add libvpx support for windows Library

### ISSUE THREAD

**Issue by se7enXF** [NON906/fftools_lib#1]
- I bought the FfmpegUnity tool from the unity store. Thank you so much for developing this tool. It works very well.  
- I want to record video in webm format, but it only works with linux build. The windows editor will prompt a parameter error. I opened **Print Error** and found that windows library compiled without libvpx support on. I also used the windows Build in Binary you provided, which could record but the video frame rate was abnormal. The recorded video flashed away, and the video that was supposed to last 10 seconds played for only two seconds. Recording as mp4 is fine.   
- In addition, I tried using [Ffmpeg-windows-build-helpers](https://github.com/NON906/ffmpeg-windows-build-helpers) compile ffmpeg Library myself, but I haven't been able to do that because of network problems.
- Therefore, I hope you can update the windows Library by enabling libvpx, after all, windows and linux libraries should be as consistent as possible. And unity supports webm natively.

**Comment by NON906** [comment]
Updated [ffmpeg-windows-build-helpers](https://github.com/NON906/ffmpeg-windows-build-helpers).

And I have prepared a build with the following options.
```
./cross_compile_ffmpeg.sh --build-ffmpeg-static=n --build-ffmpeg-shared=y --enable-gpl=n --ffmpeg-git-checkout-version=n5.1.1 --build-svt=y
```
DL: [FfmpegUnity_windows_webm.zip](https://github.com/NON906/fftools_lib/files/10728784/FfmpegUnity_windows_webm.zip)

**Comment by se7enXF** [comment]
@NON906 Thank you very much! The FfmpegUnity_windows_webm.zip you provided works good.

**Comment by se7enXF** [comment]
- @NON906 Sorry to reopen this issue. I meet the same problem when update FfmpegUnity to v2.5. If i use the upper DLL you prepared, some  missing function entry problems will raise. You add some new function in v2.5. So, I hope you can compile the DLL that supports libvpx for me again. Looking forward to your reply. 
- I need to explain that due to network reasons, the compilation process of ffmpeg-windows-build-helpers always goes wrong. So I have to ask your help again.

**Comment by se7enXF** [comment]
- Finally, I downloaded all the dependencies of [Ffmpeg-windows-build-helpers](https://github.com/NON906/ffmpeg-windows-build-helpers) manually and built it successfully. But meet some problems in building [fftools_lib](https://github.com/NON906/fftools_lib). I use CMake in windows11 generate CMakeFiles. I tried to use MinGW make and VS2019/VS2022 to build fftools_lib, but all failed. Thers is no documentation. Is fftools_lib built in Windows? I tried Ubuntu20.04  and CMake passed WIN32 part in CMakeLists.txt. 
- And I am confused by "For Windows, Mac (Library) and Linux(Library), replace generated 1. from 2. and execute it". Which one should be replaced with that one？Maybe you should provide a complete document.

**Comment by NON906** [comment]
I have attached the build.
DL: 
[FfmpegUnity_webp_ver2.5_x64.zip](https://github.com/NON906/fftools_lib/files/10938169/FfmpegUnity_webp_ver2.5_x64.zip)
[FfmpegUnity_webp_ver2.5_x86.zip](https://github.com/NON906/fftools_lib/files/10938171/FfmpegUnity_webp_ver2.5_x86.zip)

Also, as you said, the information was insufficient, so I plan to add a README.md.

**Comment by NON906** [comment]
I have added README.md.
c95adff04979f1c4860b1aec7f092c54e2d30b3c

**Comment by se7enXF** [comment]
Thank you very much! It works very well with the new DLL.  
I read the README you newly added, and I will try to build DLL according to it.
