### ISSUE TITLE
The audio and image are out of sync

### ISSUE THREAD

**Issue by se7enXF** [NON906/fftools_lib#3]
Here is two problems: 
- The audio and image are out of sync in recorded video.  The latency is about 0.2s to 1s  at random, and the audio is always faster than image. 
- Video image is stuck sometimes, but audio is fine. Perhaps this issue led to the previous one. 

Is there a good way to Optimize this issue?

**Comment by NON906** [comment]
What happens if I change it to:

Assets/FfmpegUnity/Scripts/Imp/FfmpegCaptureImpWinLib.cs Line 120-123

```csharp
                if (unitybuf_count_dll(handle) <= 0)
                {
                    unitybuf_write_dll(handle, buffer, buffer.Length);
                }
```

to

```csharp
                unitybuf_write_dll(handle, buffer, buffer.Length);
```

**Comment by se7enXF** [comment]
It works better. Thanks!
