### ISSUE TITLE
How can i switch the audio track in playing  a video with  multiple audio tracks？

### ISSUE THREAD

**Issue by ehyea** [NON906/fftools_lib#4]
i try use  -ast audio_stream_specifier， but it does not work

**Comment by NON906** [comment]
Excuse me, but could you please explain what steps/files and how it doesn't work?
Also, does it work with ``FfplayCommand.StreamCycleChannel(1);``?

**Comment by ehyea** [comment]
You can try this url https://cdn2-game-hd1.huchihuchi.com/wdpc/Videos/hd/04766ac547adb62c6df833b26c20f616.mp4
this video has two audio tracks，how can i specified the second audio track when play it？

**Comment by NON906** [comment]
I've checked the video files and both audio tracks seem to be the same.

Also, I tried ``-ast 2`` and ``-ast 3`` with the following video file, and different sounds were played normally.

https://cdn.media.ccc.de/congress/2019/h264-hd/36c3-11235-eng-deu-fra-36C3_Infrastructure_Review_hd.mp4
(CC-BY: https://media.ccc.de/v/36c3-11235-36c3_infrastructure_review)

Therefore, the video file may be the cause, so please check it again.
