### ISSUE TITLE
Unity crashes when RTSP is closed and opened a few times.

### ISSUE THREAD

**Issue by Mercury-Leo** [NON906/fftools_lib#6]
Unity Crashes whenever you stop and start a stream.

Options used: -rtsp_transport tcp -probesize 32 -flags low_delay -vf setpts=0

To reproduce:
1. Start a RTSP stream in FfplayRenderTexture/FfplayTexture
2. Stop the stream
3. Start the same stream
4. Unity crash

It usually crashes with this stack trace:
```
========== OUTPUTTING STACK TRACE ==================

0x00007FFEAAE9B7C4 (avfilter-8) avfilter_graph_dump
0x00007FFEAAE9CB9E (avfilter-8) avfilter_graph_parse_ptr
0x00007FFEE5BC96C0 (libffmpegDll) ffplay_set_audio_spec_size
0x00007FFEE5BCA0E3 (libffmpegDll) ffplay_set_audio_spec_size
0x00007FFEE5BCAF9D (libffmpegDll) ffplay_set_audio_spec_size
0x00007FFF1B2B4D53 (libwinpthread-1) pthread_create_wrapper
0x00007FFF22CBE634 (msvcrt) beginthreadex
0x00007FFF22CBE70C (msvcrt) endthreadex
0x00007FFF23A3269D (KERNEL32) BaseThreadInitThunk
0x00007FFF24ECA9F8 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========
```

This happens even with no Audio Component attached.

Using the profiler, we can see that we get two threads when a stream is running:
![image](https://user-images.githubusercontent.com/19935785/235433622-a8c562e8-3d4e-48c4-b7e0-f8e75632e031.png)

After closing and opening the stream again, two new threads are created but the threads from the previous stream are still present.

To fix the crash I added these to the Dispose method:

```
 protected virtual void Dispose()
        {
            _source.Cancel();

            if (_initCoroutine != null)
            {
                StopCoroutine(_initCoroutine);
            }
           //...
        }

```
I also changed Thread and CallEventThread to tasks and they run on the threadpool and gave them a cancellation token.

This may have fixed the crashes but theres a bigger problem. Whenever I stop and start a stream, the CPU usage goes up by a lot and stays like that until Unity is closed (even not in playmode).
For example:
Start a stream, close the stream, open the same stream. Repeat 4+ times.
This results in 100% CPU usage and it won't clear even when exiting playmode and Unity has to be closed via task manager.
When the stream is stopped, the CPU usage goes down, but once it's restarted, the CPU usage a lot higher, and continues like this for each stop and start.

Possible problems:
1. When a stream stops, it doesn't close the stream and once start is called again, it is assigned a new ID and starts a new stream while the old one is still in usage.
2. The native wrapper for FFMPEG has a memory leak somewhere.
3. Calling ffplay_stop is not enough to clear the stream.

**Comment by NON906** [comment]
Apparently, using ``-vf setpts=0`` causes this problem.
What if you use ``-fflags nobuffer`` instead?

**Comment by Mercury-Leo** [comment]
OK, yeah it was the options that caused the crash, which is strange as I wanted to get as little delay as possible.
Thanks.

By the way there is a leak and I found where it's coming from.
In Dispose:

```
        public virtual void Dispose()
        {
            if (thread_ == null || thread_.ThreadState != ThreadState.Running)
            {
                currentId_ = -1;
            }

            if (currentId_ > 0)
            {
                ffplay_stop(currentId_);
                currentId_ = -1;
            }

            streamingAssetsCopyPathClass_.ExecuteDeleteAssets();
        }
```

You change the currentId to -1 before it actually closes it, so the stream never actually closes.
In thread, it won't finish the execution until ffplay_start actually ended.

So by just even removing the first if block, this solves most of the problems as the stream will close correctly.

```
public virtual void Dispose()
        {
            if (currentId_ > 0)
            {
                ffplay_stop(currentId_);
                currentId_ = -1;
            }

            streamingAssetsCopyPathClass_.ExecuteDeleteAssets();
        }
```

**Comment by NON906** [comment]
Thank you for your report.
It will be reflected in the next version.
