### ISSUE TITLE
libopenh264.so requires GLIBC_2.34 not work on Ubuntu 18.04 and Ubuntu 20.04

### ISSUE THREAD

**Issue by se7enXF** [NON906/fftools_lib#7]
As say in title, the FFmpeg for Unity v2.7 add libopenh264.so in Linux build, which result the issue. The previous versions (<=2.5) work well. Could you please provide a libopenh264.so works on GLIBC_2.30 and before?

**Comment by se7enXF** [comment]
I tested the following way and it worked. But I think optimizing from building libopenh264.so is a better solution. 

Add a higher version of libc source, updating libc from apt
```bash
# Add the following line at the end of /etc/apt/
deb xxxx.xxxx.com/ubuntu jammy main

# update apt and install libc
apt update
apt install libc6
```

**Comment by se7enXF** [comment]
> I tested the following way and it worked. But I think optimizing from building libopenh264.so is a better solution.
> 
> Add a higher version of libc source, updating libc from apt
> 
> ```shell
> # Add the following line at the end of /etc/apt/
> deb xxxx.xxxx.com/ubuntu jammy main
> 
> # update apt and install libc
> apt update
> apt install libc6
> ```

Installing higher version of libc meet the libopenh264.so requirements, but broke the OpenGL. This way is not work for me. I think build this tool in ubuntu 20.04/18.04 will fix the issue.

**Comment by NON906** [comment]
Downgraded the libopenh264 library to the version that supports Ubuntu20.04.
Please import and check it.
[FfmpegUnity_patch_openh264_linux.zip](https://github.com/NON906/fftools_lib/files/11663447/FfmpegUnity_patch_openh264_linux.zip)

**Comment by se7enXF** [comment]
> Downgraded the libopenh264 library to the version that supports Ubuntu20.04. Please import and check it. [FfmpegUnity_patch_openh264_linux.zip](https://github.com/NON906/fftools_lib/files/11663447/FfmpegUnity_patch_openh264_linux.zip)

Thanks. It is working.
