### ISSUE TITLE
URP support required

### ISSUE THREAD

**Issue by se7enXF** [NON906/fftools_lib#9]
I have a project that mush run in URP(Universal Render Pipeline). I try to record video but no files generated. We can find in [Unity Doc](https://docs.unity3d.com/ScriptReference/Camera.OnRenderImage.html) with this: "OnRenderImage is not supported in the Scriptable Render Pipeline. "  

More and more projects are using URP, and I think this tool also needs to be upgraded to support it.

**Comment by NON906** [comment]
I would like to ask, is it the same when using Video_RenderTexture?

**Comment by se7enXF** [comment]
> I would like to ask, is it the same when using Video_RenderTexture?

I have not tried. I am trying to Blit camera into a RenderTexture without processing OnRenderImage.

**Comment by se7enXF** [comment]
@NON906 
I solve the problem. Using `ScriptableRenderPass` to Blit the camera texture into RenderTexture, and use RenderTexture as FFmpeg recording target.
